services:
  - type: web
    name: zidane-trans
    env: php
    buildCommand: "composer install --no-dev && php artisan key:generate && php artisan config:cache"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    plan: free
    region: oregon
    branch: main
    envVars:
    - key: APP_ENV
      value: production
    - key: APP_DEBUG
      value: false
    - key: APP_URL
      value: https://zidane-trans.onrender.com
    - key: DB_CONNECTION
      value: mysql
    - key: DB_HOST
      value: db4free.net
    - key: DB_PORT
      value: 3306
    - key: DB_DATABASE
      value: zidan_trans
    - key: DB_USERNAME
      value: zidan_user
    - key: DB_PASSWORD
      value: zidan123
